const Screens = {
   HOME_PAGE: 'HOME_PAGE',
   TODO_DETAILS_PAGE: 'TODO_DETAILS_PAGE',
   CREATE_TODO_PAGE: 'CREATE_TODO_PAGE',
   DAILY_TODO_LIST_PAGE: 'DAILY_TODO_LIST_PAGE',
   WEEKLY_TODO_LIST_PAGE: 'WEEKLY_TODO_LIST_PAGE',
   MONTHLY_TODO_LIST_PAGE: 'MONTHLY_TODO_LIST_PAGE',
}

export default Screens
 